services:
  backend:
    build: ./backend
    container_name: cinema_backend
    restart: unless-stopped
    env_file: ./backend/.env
    # Pass MONGO_URI from .env file
    ports:
      - '3001:3001'
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - cinema_net

  frontend:
    build: ./frontend
    container_name: cinema_frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - cinema_net

networks:
  cinema_net:
    driver: bridge
